name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::592115245551:role/github-push-ecr-role
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        if: ${{ github.ref == 'refs/heads/master' }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: "592115245551.dkr.ecr.eu-central-1.amazonaws.com/content-pipeline/backup:latest,592115245551.dkr.ecr.eu-central-1.amazonaws.com/content-pipeline/backup:${{ github.run_number }}"
